services:
  taxually.api:
    image: taxually.api
    build:
      context: .
      dockerfile: Taxually.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 #https is not configured for simplicity. If necessary, refer to https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-8.0
    ports:
      - 5292:8080
